/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class BytesTestTableUpdate
        : TypedRecordUpdate<Tuple<BytesTestTable?, BytesTestTable?>> { }

    public class BytesTestTable : IMudTable
    {
        public readonly static TableId ID = new("", "BytesTest");

        public override TableId GetTableId()
        {
            return ID;
        }

        public string? value;

        public override Type TableType()
        {
            return typeof(BytesTestTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(BytesTestTableUpdate);
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (string)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var valueValue = (string)table["value"];

            value = valueValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            BytesTestTableUpdate update = (BytesTestTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new BytesTestTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<BytesTestTable?, BytesTestTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            BytesTestTable? current = null;
            BytesTestTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new BytesTestTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (string)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new BytesTestTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new BytesTestTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (string)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new BytesTestTable { value = null, };
                }
            }

            return new Tuple<BytesTestTable?, BytesTestTable?>(current, previous);
        }
    }
}
