/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class PositionTableUpdate : TypedRecordUpdate<Tuple<PositionTable?, PositionTable?>> { }

    public class PositionTable : IMudTable
    {
        public readonly static string ID = "Position";
        public static RxTable PositionRxTable
        {
            get { return NetworkManager.Datastore.tableNameIndex[ID]; }
        }

        public override string GetTableId()
        {
            return ID;
        }

        public override Type TableType()
        {
            return typeof(PositionTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(PositionTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            PositionTable other = (PositionTable)obj;

            if (other == null)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters) { }

        public override void RecordToTable(RxRecord record)
        {
            var table = record.value;
            //bool hasValues = false;
        }

        public static Tuple<PositionTable?, PositionTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            PositionTable? current = null;
            PositionTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new PositionTable { };
                }
                catch (InvalidCastException)
                {
                    current = new PositionTable { };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new PositionTable { };
                }
                catch (InvalidCastException)
                {
                    previous = new PositionTable { };
                }
            }

            return new Tuple<PositionTable?, PositionTable?>(current, previous);
        }
    }
}
