/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class StateTableUpdate : TypedRecordUpdate<Tuple<StateTable?, StateTable?>> { }

    public class StateTable : IMudTable
    {
        public readonly static TableId ID = new("", "State");

        public override TableId GetTableId()
        {
            return ID;
        }

        public byte? value;

        public override Type TableType()
        {
            return typeof(StateTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(StateTableUpdate);
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (byte)functionParameters[0];
        }

        public override void RecordToTable(Record record)
        {
            var table = record.value;
            //bool hasValues = false;

            var valueValue = (byte)table["value"];

            value = valueValue;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            StateTableUpdate update = (StateTableUpdate)tableUpdate;
            return update?.TypedValue.Item1;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new StateTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<StateTable?, StateTable?> MapUpdates(Tuple<Property?, Property?> value)
        {
            StateTable? current = null;
            StateTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new StateTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (byte)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new StateTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new StateTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (byte)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new StateTable { value = null, };
                }
            }

            return new Tuple<StateTable?, StateTable?>(current, previous);
        }
    }
}
