/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class StateTableUpdate : TypedRecordUpdate<Tuple<StateTable?, StateTable?>> { }

    public class StateTable : IMudTable
    {
        public readonly static string ID = "State";
        public static RxTable StateRxTable
        {
            get { return NetworkManager.Datastore.tableNameIndex[ID]; }
        }

        public override string GetTableId()
        {
            return ID;
        }

        public override Type TableType()
        {
            return typeof(StateTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(StateTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            StateTable other = (StateTable)obj;

            if (other == null)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters) { }

        public override void RecordToTable(RxRecord record)
        {
            var table = record.value;
            //bool hasValues = false;
        }

        public static Tuple<StateTable?, StateTable?> MapUpdates(Tuple<Property?, Property?> value)
        {
            StateTable? current = null;
            StateTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new StateTable { };
                }
                catch (InvalidCastException)
                {
                    current = new StateTable { };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new StateTable { };
                }
                catch (InvalidCastException)
                {
                    previous = new StateTable { };
                }
            }

            return new Tuple<StateTable?, StateTable?>(current, previous);
        }
    }
}
