/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class TesterTableUpdate : TypedRecordUpdate<Tuple<TesterTable?, TesterTable?>> { }

    public class TesterTable : IMudTable
    {
        public readonly static string ID = "Tester";
        public static RxTable TesterRxTable
        {
            get { return NetworkManager.Datastore.tableNameIndex[ID]; }
        }

        public override string GetTableId()
        {
            return ID;
        }

        public override Type TableType()
        {
            return typeof(TesterTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(TesterTableUpdate);
        }

        public override bool Equals(object? obj)
        {
            TesterTable other = (TesterTable)obj;

            if (other == null)
            {
                return false;
            }
            return true;
        }

        public override void SetValues(params object[] functionParameters) { }

        public override void RecordToTable(RxRecord record)
        {
            var table = record.value;
            //bool hasValues = false;
        }

        public static Tuple<TesterTable?, TesterTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            TesterTable? current = null;
            TesterTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new TesterTable { };
                }
                catch (InvalidCastException)
                {
                    current = new TesterTable { };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new TesterTable { };
                }
                catch (InvalidCastException)
                {
                    previous = new TesterTable { };
                }
            }

            return new Tuple<TesterTable?, TesterTable?>(current, previous);
        }
    }
}
